### ISSUE TITLE
Need bash vim mode.

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack#33]
I keep hitting jj trying to get my bash into vim visual mode and it isn't working :(

**Comment by DanielOchoa** [comment]
are you running vim or nvim? We'll need to change vim to run nvim. nvim uses .nvimrc and we haven't simlinked that as well.

**Comment by MatthewHager** [comment]
Should we just switch to nvim permanently? If so, we can alias vim to nvim and set everything up. If not, we should remove nvim because it takes a while to compile and adds time to the build. If we don't gain a lot from nvim, please remove it.

**Comment by DanielOchoa** [comment]
4c8d3ca6f946c056690870fc4bc6f6f2e7a135b0 removes nvim since it seems to have some issues with spf13 settings. Those can be resolved by updating nvim after installing it (through pip upgrade), and when running nvim for the first time it will promp you to create some files. Not worth it IMO.

Anyway, this is now fixed.
